name: Docker Image CI

on:
  push:
    branches: [ "main", "staging" ]  # 添加 push 事件
  pull_request:
    branches: [ "main", "dev", "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-app:latest  # 简化标签
